from typing import Callable, Dict, Any
import torch
from torch import nn
from torch.utils.checkpoint import checkpoint

from .base import NeuralIsometry
from infidictionary.networks import ConditionalField, SinusoidalTimeEmbedding
from infidictionary.networks.base import _build_mlp


class EulerianIsometry(NeuralIsometry):
    """Learned isometry of ``L²`` generated by a finite-rank skew-adjoint flow.

    See *Learning Orthonormal Bases for Function Spaces*
    (https://arxiv.org/abs/2605.19959).

    The map is the time-``T`` flow of

        ``ẏ = 𝔅 y``,   ``𝔅 = Φ B Φ*``,

    where ``Φ z = Σ_r U_r z_r`` synthesizes a function from ``R`` coefficients
    against the learned basis field ``U(t, ·)``, ``Φ*`` is its adjoint in the
    weighted ``L²`` inner product (a Monte-Carlo average over the sampled
    coordinates), and ``B = ½·Δt·a·(K_R - K_Rᵀ)`` is skew. Because ``𝔅`` is
    skew-adjoint the flow is orthogonal *by construction* — the Gram matrix of
    any set of functions is preserved exactly, not merely penalized toward it —
    and the inverse map is the same flow with time reversed, which is why
    ``pullback`` simply flips ``tspan``.

    Each step is integrated with the Cayley transform ``y ↦ (I - M)⁻¹(I + M) y``
    (``M = ½·Δt·𝔅``), the Padé(1,1) approximant of ``exp(Δt·𝔅)``. Unlike a
    truncated exponential it is exactly orthogonal at every step size, so the
    isometry property survives coarse discretization. See ``_joint_cayley_step``
    for how the infinite-dimensional inverse collapses to an ``R×R`` solve.

    Gradients are obtained by recomputation, not by storing the trajectory: with
    ``gradient_checkpointing`` each Cayley step is replayed during the backward
    pass (``torch.utils.checkpoint`` in ``_run_ode``), making memory ``O(1)``
    rather than ``O(num_steps)``. This plays the role the adjoint method plays
    for neural ODEs, and yields the same gradient — but it recomputes each
    *discrete* step exactly instead of integrating a continuous adjoint
    backwards, so it does not accumulate the reverse-pass integration error that
    makes true adjoint solvers inconsistent with their own forward pass.
    """

    def __init__(
        self,
        coords_dim: int,
        channels_dim: int,
        rank: int,
        base_acceleration: float,
        scalar_field_partial: Callable[[Dict[str, Any]], ConditionalField],
        gradient_checkpointing: bool = False,
        n_time_freqs: int = 16,
        kr_hidden_dims: tuple = (64, 64),
        max_gen_norm: float | None = None,
        # Healthy 1-D runs at base_acceleration=10 sit at ‖G·B_op‖ ≈ 80-2000, so
        # 1e4 is a no-op there and engages only well outside that regime (e.g.
        # base_acceleration=1000, which is ~100x higher).
        substep_tol: float = 1e4,
        max_substeps: int = 64,
    ):
        super().__init__()

        self.time_embedding = SinusoidalTimeEmbedding(n_time_freqs)
        emb_dim = self.time_embedding.out_dim

        self.function_field = scalar_field_partial(
            coords_dim=coords_dim,
            output_dim=channels_dim,
            rank=rank,
            cond_dim=emb_dim,
        )

        self.coords_dim = coords_dim
        self.channels_dim = channels_dim
        self.rank = rank
        self.gradient_checkpointing = gradient_checkpointing
        self.base_acceleration = base_acceleration
        self.max_gen_norm = max_gen_norm
        self.substep_tol = substep_tol
        self.max_substeps = max_substeps
        self._collect_diagnostics = False
        self._diagnostics: dict[str, float] = {}
        self._num_steps = 0
        self.register_buffer("tspan", torch.tensor([]), persistent=False)

        self.kr_mlp = _build_mlp(
            emb_dim,
            rank * rank,
            kr_hidden_dims,
            nn.SiLU,
            use_batchnorm=False,
            use_rmsnorm=True,
            bias=True,
        )

    def _compute_kr(self, t_emb: torch.Tensor) -> torch.Tensor:
        """Map time embeddings to ``(R, R)`` matrices."""
        return self.kr_mlp(t_emb).view(-1, self.rank, self.rank)

    def _joint_cayley_step(
        self,
        t0: float,
        t1: float,
        U: torch.Tensor,
        K_R: torch.Tensor,
        logabsdet: torch.Tensor,
        values: torch.Tensor,
        acceleration: float,
    ) -> torch.Tensor:
        """Apply one Cayley step of the finite-rank skew flow.

        Shapes — ``U: (N, R, C)`` the basis field at this timestep, ``K_R: (R, R)``,
        ``logabsdet: (N,)`` the log-density of the coordinate sample,
        ``values: (B, N, C)``; returns ``(B, N, C)``.

        Computes ``y ↦ (I - M)⁻¹(I + M) y`` with ``M = β Φ A Φ*``, ``β = ½·Δt·a``
        and ``A = K_R - K_Rᵀ`` skew. Writing ``Φ`` for synthesis against ``U`` and
        ``Φ*`` for the weighted-``L²`` analysis (the ``exp_lad``-weighted einsums
        below, each a Monte-Carlo average over the ``N`` sample points):

        1. Normalize each ``U_r`` to unit weighted norm, so ``G`` has unit diagonal.
        2. ``(I + M) y`` explicitly → ``y_pre``. Cheap: project (``c_proj: (B, R)``),
           apply ``B_op``, synthesize back.
        3. ``(I - M)⁻¹`` via the push-through/Woodbury identity,

               ``(I - Φ B Φ*)⁻¹ = I + Φ B (I_R - G B)⁻¹ Φ*``,   ``G = Φ*Φ``,

           so the inverse of an operator on an ``N·C``-dimensional function space
           reduces to the ``R×R`` system ``(I_R - G·B_op) z_p = tilde_c``. Cost is
           ``O(R³ + B R²)`` instead of ``O((N·C)³)``.

        The batch rides along as multiple right-hand sides: ``tilde_c`` is
        transposed to ``(R, B)`` for the solve and back afterwards.

        When ``‖G·B_op‖`` is large the step is split into ``m`` substeps of
        ``B_op/m``. Cayley is exactly orthogonal at any step size, so this never
        weakens the isometry; and since ``Cay(B/m)^m → exp(B)``, a finer split is
        a strictly more faithful approximation of the same flow, not a different
        one. ``U`` and ``K_R`` are already frozen across the step by ``_run_ode``,
        so substepping refines only the exponential, leaving the generator — and
        hence the meaning of the learned parameters — untouched.

        The split is chosen from ``‖G·B_op‖``, a norm and therefore invariant
        under the sign flip that distinguishes pullback from pushforward. Both
        directions pick the same ``m``, so they remain exact inverses.
        """
        values = values.to(U.dtype)
        N, R, _ = U.shape
        beta = 0.5 * (t1 - t0) * acceleration
        exp_lad = logabsdet.exp().to(U.dtype)

        g_diag = torch.einsum("nrc,nrc,n->r", U, U, exp_lad) / N
        U = U / (g_diag.clamp(min=1e-12).sqrt()[None, :, None])

        A = K_R - K_R.transpose(-1, -2)
        if self.max_gen_norm is not None:
            scale = (self.max_gen_norm / (torch.linalg.norm(A) + 1e-12)).clamp(max=1.0)
            A = A * scale
        B_op = beta * A

        G = torch.einsum("nrc,nsc,n->rs", U, U, exp_lad) / N
        I_R = torch.eye(R, device=U.device, dtype=U.dtype)

        # Split the step so that each substep's ‖G·B‖ stays under the tolerance.
        # Detached and norm-based: it selects a quadrature, not a direction, and
        # must agree between pushforward and pullback.
        with torch.no_grad():
            gb = torch.linalg.matrix_norm(G @ B_op, ord=2)
            n_sub = int(torch.ceil(gb / self.substep_tol).clamp(1, self.max_substeps).item())

        B_sub = B_op / n_sub
        y = values
        for _ in range(n_sub):
            c_proj = torch.einsum("nrc,bnc,n->br", U, y, exp_lad) / N
            Bc = torch.einsum("rs,bs->br", B_sub, c_proj)
            y_pre = y + torch.einsum("nrc,br->bnc", U, Bc)

            tilde_c = torch.einsum("nrc,bnc,n->br", U, y_pre, exp_lad) / N
            Msys = I_R - G @ B_sub
            z_p = torch.linalg.solve(Msys, tilde_c.transpose(-1, -2)).transpose(-1, -2)
            z = torch.einsum("rs,bs->br", B_sub, z_p)
            y = y_pre + torch.einsum("nrc,br->bnc", U, z)

        if self._collect_diagnostics:
            with torch.no_grad():
                sv = torch.linalg.svdvals(Msys.float())
                self._diagnostics["cond_msys"] = max(
                    self._diagnostics.get("cond_msys", 0.0),
                    (sv.amax() / sv.amin().clamp(min=1e-30)).item(),
                )
                self._diagnostics["min_eig_gram"] = min(
                    self._diagnostics.get("min_eig_gram", float("inf")),
                    torch.linalg.eigvalsh(G.float()).amin().item(),
                )
                self._diagnostics["max_substeps_used"] = max(
                    self._diagnostics.get("max_substeps_used", 0), n_sub
                )

        return y

    def _run_ode(
        self,
        coords: torch.Tensor,
        logabsdet: torch.Tensor,
        f: torch.Tensor,
        tspan: torch.Tensor,
    ) -> torch.Tensor:
        N = f.shape[1]
        use_ckpt = self.gradient_checkpointing and self.training
        t_mid = (tspan[:-1] + tspan[1:]) / 2
        t_mid = t_mid.to(f.device)

        all_t_emb = self.time_embedding(t_mid)
        all_kr = self._compute_kr(all_t_emb)

        for i, (t0, t1) in enumerate(zip(tspan[:-1].tolist(), tspan[1:].tolist())):
            K_R = all_kr[i]
            t_emb_step = all_t_emb[i]

            def step(v, _t_emb=t_emb_step, _t0=t0, _t1=t1, _K_R=K_R):
                t_emb_N = _t_emb[None].expand(N, -1)
                U = self.function_field(t_emb_N, coords)
                return self._joint_cayley_step(
                    _t0, _t1, U, _K_R, logabsdet, v, self.base_acceleration
                )

            f = checkpoint(step, f, use_reentrant=False) if use_ckpt else step(f)

        return f

    def pop_diagnostics(self) -> dict[str, float]:
        """Return and clear the numerical diagnostics gathered since the last call.

        Enables collection on first use, so a caller that never asks pays nothing.
        """
        self._collect_diagnostics = True
        out, self._diagnostics = self._diagnostics, {}
        return out

    def shuffle_model_state(self, num_steps: int | None = None):
        """Resample the time-discretization grid the flow is integrated on.

        In training the nodes are ``num_steps`` sorted uniform draws, so every
        call integrates over a different, non-uniform grid. This stops the model
        from overfitting to one particular discretization — it has to represent
        the same isometry whatever step sizes it is evaluated with. In eval the
        grid is a fixed ``linspace`` so results are reproducible.
        """
        if num_steps is not None:
            self._num_steps = num_steps
        if self._num_steps == 0:
            raise ValueError("Call shuffle_model_state with num_steps > 0 first.")
        if self.training:
            t_rand = torch.rand(self._num_steps)
            self.tspan = torch.sort(t_rand)[0]
        else:
            self.tspan = torch.linspace(0, 1, self._num_steps)

    def pushforward(
        self,
        src_coords: torch.Tensor,
        src_logabsdet: torch.Tensor,
        src_field: torch.Tensor,
        rot_start_time: float,
        rot_end_time: float,
    ):
        tspan = self.tspan * (rot_end_time - rot_start_time) + rot_start_time
        tgt_field = self._run_ode(src_coords, src_logabsdet, src_field, tspan)
        return src_coords, src_logabsdet, tgt_field

    def pullback(
        self,
        tgt_coords: torch.Tensor,
        tgt_logabsdet: torch.Tensor,
        tgt_field: torch.Tensor,
        rot_start_time: float,
        rot_end_time: float,
    ):
        tspan = self.tspan.flip(0) * (rot_end_time - rot_start_time) + rot_start_time
        src_field = self._run_ode(tgt_coords, tgt_logabsdet, tgt_field, tspan)
        return tgt_coords, tgt_logabsdet, src_field
